/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HouseService } from "../house.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HouseCreateInput } from "./HouseCreateInput";
import { HouseWhereInput } from "./HouseWhereInput";
import { HouseWhereUniqueInput } from "./HouseWhereUniqueInput";
import { HouseFindManyArgs } from "./HouseFindManyArgs";
import { HouseUpdateInput } from "./HouseUpdateInput";
import { House } from "./House";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HouseControllerBase {
  constructor(
    protected readonly service: HouseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: House })
  @nestAccessControl.UseRoles({
    resource: "House",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: HouseCreateInput): Promise<House> {
    return await this.service.create({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        amenity: true,
        area: true,
        bath: true,
        bed: true,
        car: true,
        category: true,
        cell: true,
        city: true,
        createdAt: true,
        desc: true,
        id: true,
        mapData: true,
        photos: true,
        street: true,
        tipo: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        ward: true,
        whatsapp: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [House] })
  @ApiNestedQuery(HouseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "House",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<House[]> {
    const args = plainToClass(HouseFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        amenity: true,
        area: true,
        bath: true,
        bed: true,
        car: true,
        category: true,
        cell: true,
        city: true,
        createdAt: true,
        desc: true,
        id: true,
        mapData: true,
        photos: true,
        street: true,
        tipo: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        ward: true,
        whatsapp: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: House })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "House",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: HouseWhereUniqueInput
  ): Promise<House | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        amenity: true,
        area: true,
        bath: true,
        bed: true,
        car: true,
        category: true,
        cell: true,
        city: true,
        createdAt: true,
        desc: true,
        id: true,
        mapData: true,
        photos: true,
        street: true,
        tipo: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        ward: true,
        whatsapp: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: House })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "House",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: HouseWhereUniqueInput,
    @common.Body() data: HouseUpdateInput
  ): Promise<House | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          amenity: true,
          area: true,
          bath: true,
          bed: true,
          car: true,
          category: true,
          cell: true,
          city: true,
          createdAt: true,
          desc: true,
          id: true,
          mapData: true,
          photos: true,
          street: true,
          tipo: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          ward: true,
          whatsapp: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: House })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "House",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: HouseWhereUniqueInput
  ): Promise<House | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          amenity: true,
          area: true,
          bath: true,
          bed: true,
          car: true,
          category: true,
          cell: true,
          city: true,
          createdAt: true,
          desc: true,
          id: true,
          mapData: true,
          photos: true,
          street: true,
          tipo: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          ward: true,
          whatsapp: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
